### ISSUE TITLE
updating httpoison?

### ISSUE THREAD

**Issue by bitboxer** [liefery/bugsnex#32]
👋  I am currently looking into adding this to a side project of mine and saw that bugsnex still depends on an old version of `httpoison`. Is this on purpose? Or can I create a little PR that changes this?

**Comment by PragTob** [comment]
:wave: 

Sure, please go ahead otherwise we might also get to it, as we should update :) Looking at the changelog it should be relatively easy and I think our usage isn't super fancy.
