### ISSUE TITLE
Erlang error %Phoenix.Router.NoRouteError reported on 404 after upgrade to plug_cowboy 2

### ISSUE THREAD

**Issue by adamniedzielski** [liefery/bugsnex#36]
After upgrade to plug_cowboy 2, 404 responses started to appear as errors in Bugsnag:

```
Erlang error: {{%Phoenix.Router.NoRouteError{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: [#Function<1.1812729/1 in Plug.Logger.call/2>], body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "fulfillment-staging.liefery.com", method: "GET", owner: #PID<0.2309.0>, params: %{}, path_info: ["css", "vendor.css"], path_params: %{}, port: 80, private: %{Fulfillment.Router => {[], %{}}, :phoenix_endpoint => Fulfillment.Endpoint, :phoenix_router => Fulfillment.Router, :plug_session_fetch => #Function<1.58261320/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {10, 10, 1, 5}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "text/css,*/*;q=0.1"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9,de;q=0.8"}

[redacted]
```

This didn't happen when using plug_cowboy 1.

It looks like multiple other libraries for error tracking services experienced the similar problem:
- https://github.com/appsignal/appsignal-elixir/issues/417
- https://github.com/getsentry/sentry-elixir/issues/328
- https://github.com/honeybadger-io/honeybadger-elixir/issues/193

I found the content in https://github.com/appsignal/appsignal-elixir/issues/417 particularly informative. [Here](https://github.com/appsignal/appsignal-elixir/issues/417#issuecomment-439876201) is the explanation and [here](https://github.com/appsignal/appsignal-elixir/issues/417#issuecomment-443695327) is a suggestion to switch from listening to Erlang's error_logger(which we do [here](https://github.com/liefery/bugsnex/blob/51b8aafacef99504cbfe6c5e29c473741530c1bd/lib/bugsnex.ex#L12)) to listening to Elixir's Logger.

We should investigate if the suggestion fixes the problem.

**Comment by bitboxer** [comment]
I also would love to see this one fixed. If you need any help doing so, please ping here. I would love to chip in a bit of my time for this.

**Comment by adamniedzielski** [comment]
@bitboxer we reverted to plug_cowboy 1 so that's not a pressing bug for us 😆Feel free to submit a PR

**Comment by bitboxer** [comment]
So after looking into it, changing the logger like [here](https://github.com/appsignal/appsignal-elixir/pull/454/files) won't help that much. We just need to filter for the status code. Credo changed the behaviour what is raised as an exception.

For example like [here](https://github.com/appsignal/appsignal-elixir/blob/develop/lib/appsignal/error_handler.ex#L44) or [here](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/plug.ex#L59) inside of the plug. 

What do you think? Would the first approach with everything < 500 should not be reported to bugsnag be okay?

**Comment by irmela** [comment]
@bitboxer Thanks for looking into it. I think the approach with not reporting < 500 is good enough. Would you be willing to submit a PR?

**Comment by adamniedzielski** [comment]
👍 sounds good to me.

Thanks for pointing us to https://github.com/appsignal/appsignal-elixir/pull/454. I tried to understand it, but I still have some unanswered questions:
1. what's the advantage of using `:logger` over `:error_logger`?
2. why Elixir `Logger` doesn't have a way to extract the error object and stacktrace? Is it a bug / missing important feature in Elixir `Logger`?

**Comment by bitboxer** [comment]
If it is still okay, I am happy to provide a PR for this.

**Comment by adamniedzielski** [comment]
Sure! I posted the questions to show my thinking processes, not necessarily to get the answers 😄
